package code 
{
	public class GameInfo 
	{
		// Game Variables
		public static var getShinyTags:Array = [ { "label": "Normal", "data": 0 }, { "label": "Shiny", "data": 1 }, { "label": "Shadow", "data": 2 } ];
		public static var getGenderTags:Array = [ { "label": "Male", "data": 1 }, { "label": "Female", "data": 2 } ];
		public static var getVersionTags:Array = [ { "label": "Gold", "data": 1 }, { "label": "Silver", "data": 2 } ];
		
		public static function buildItemList(fun:String, inS:int, inE:int, addIndex:Boolean = false):Array
		{
			var out:Array = [];
			var funC:Function = GameInfo[fun];
			for (var index:int = inS; index <= inE; index++)
			{
				var d:* = funC(index);
				if (d is Array) d = d.join(" - ");
				out.push( { "label": (addIndex ? index + ": " : "") + d, "data": index } );
			}
			return out;
		}
		
		// Start Wall Of Values...
		public static const MAP_FUNC_NAME:String = "getMapName";
		public static const MAP_INDEX_START:int = 1;
		public static const MAP_INDEX_END:int = 111;
		public static function getMapName(mapID:int):String
		{
			switch(mapID)
			{
				case 1:		return "Your Room";
				case 2:		return "Your House";
				case 3:		return "New Bark Town";
				case 4:		return "New Bark Town Lab";
				case 5:		return "Rival House";
				case 6:		return "Rival Room";
				case 7:		return "New Bark Town Other House";
				case 8:		return "New Bark Town Spot";
				case 9:		return "Route 29";
				case 10:	return "Cherrygrove City";
				case 11:	return "Route 30";
				case 12:	return "Route 31";
				case 13:	return "Dark Cave";
				case 14:	return "Route 46";
				case 15:	return "Violet City";
				case 16:	return "Sprout Tower";
				case 17:	return "Route 32";
				case 18:	return "Alph Ruins";
				case 19:	return "Alph Ruins Interior 1";
				case 20:	return "Alph Ruins Interior 2";
				case 21:	return "Route 32 2";
				case 22:	return "New Bark Town Past";
				case 23:	return "Your Room Past";
				case 24:	return "Your House Past";
				case 25:	return "New Bark Town Lab Past";
				case 26:	return "Rival House Past";
				case 27:	return "Rival Room Past";
				case 28:	return "New Bark Town Other House Past";
				case 29:	return "New Bark Town Spot Past";
				case 30:	return "Route 29 Past";
				case 31:	return "Cherrygrove City Past";
				case 32:	return "Route 30 Past";
				case 33:	return "Route 31 Past";
				case 34:	return "Dark Cave Past";
				case 35:	return "Route 46 Past";
				case 36:	return "Violet City Past";
				case 37:	return "Sprout Tower Past";
				case 38:	return "Route 32 Past";
				case 39:	return "Alph Ruins Past";
				case 40:	return "Alph Ruins Interior 1 Past";
				case 41:	return "Alph Ruins Interior 2 Past";
				case 42:	return "Route 32 2 Past";
				case 43:	return "Cherrygrove House";
				case 44:	return "Pokecenter";
				case 45:	return "Pokemart";
				case 46:	return "Cherrygrove House 2";
				case 47:	return "Cherrygrove House 3";
				case 48:	return "Route 30 House 1";
				case 49:	return "Route 30 House 2";
				case 50:	return "Violet City House 1";
				case 51:	return "Violet City House 2";
				case 52:	return "Violet City School";
				case 53:	return "Violet City Pokecenter";
				case 54:	return "Violet City Pokemart";
				case 55:	return "Violet City Gym";
				case 56:	return "Route 32 3 Past";
				case 57:	return "Route 32 Pokecenter";
				case 58:	return "Union Cave 1 Past";
				case 59:	return "Union Cave 2 Past";
				case 60:	return "Route 33 Past";
				case 61:	return "Azalea Town Past";
				case 62:	return "Azalea Town Pokecenter";
				case 63:	return "Azalea Town Pokemart";
				case 64:	return "Slowpoke Well";
				case 65:	return "Azalea Town House 1";
				case 66:	return "Azalea Town House 2";
				case 67:	return "Azalea Town Gym";
				case 68:	return "Ilex Forest Past";
				case 69:	return "Route 34 Past";
				case 70:	return "Goldenrod City Past";
				case 71:	return "Goldenrod Bike Shop Past";
				case 72:	return "Goldenrod Game Corner Past";
				case 73:	return "Goldenrod Pokecenter";
				case 74:	return "Goldenrod Mart";
				case 75:	return "Route 35 Past";
				case 76:	return "National Park Past";
				case 77:	return "Route 36 Past";
				case 78:	return "Route 37 Past";
				case 79:	return "Ecruteak City Past";
				case 80:	return "Ecruteak Center Past";
				case 81:	return "Ecruteak Mart Past";
				case 82:	return "Route 38 Past";
				case 83:	return "Route 39 Past";
				case 84:	return "Olivine City Past";
				case 85:	return "Olivine Pokecenter Past";
				case 86:	return "Olivine Pokemart Past";
				case 87:	return "Dark Cave 2";
				case 88:	return "Dark Cave 3";
				case 89:	return "Dark Cave 4";
				case 90:	return "Alph Ruins Interior 3 Past";
				case 91:	return "Alph Ruins Interior 4 Past";
				case 92:	return "Alph Ruins Interior 5 Past";
				case 93:	return "Union Cave 3 Past";
				case 94:	return "Slowpoke Well 2";
				case 95:	return "Route 42 Past";
				case 96:	return "Mt Mortar 1 Past";
				case 97:	return "Mt Mortar 2 Past";
				case 98:	return "Mahogany Town Past";
				case 99:	return "Mahogany Pokecenter Past";
				case 100:	return "Mahogany Pokemart Past";
				case 101:	return "Route 43 Past";
				case 102:	return "Route 44 Past";
				case 103:	return "Lake Of Rage Past";
				case 104:	return "Ice Path";
				case 105:	return "Sam House Past";
				case 106:	return "Blackthorn City Past";
				case 107:	return "Blackthorn Pokecenter Past";
				case 108:	return "Blackthorn Pokemart Past";
				case 109:	return "Dragon Den Past";
				case 110:	return "Route 45 Past";
				case 111:	return "Tournament Lobby Past";
			}
			return "Map #" + mapID.toString();
		}
		
		public static const EXTRA_FUNC_NAME:String = "getExtraDescription";
		public static const EXTRA_INDEX_START:int = 1;
		public static const EXTRA_INDEX_END:int = 122;
		public static function getExtraDescription(tag:int):Array
		{
			switch(tag)
			{
				case 1:		return ["Quest", "Get Poke"];
				case 2:		return ["Quest", "Save Poke"];
				case 3:		return ["Quest", "Rival Fight"];
				case 4:		return ["Quest", "Get Pokepad"];
				case 5:		return ["Quest", "Entered Route 29"];
				case 6:		return ["Quest", "Entered Cherrygrove"];
				case 7:		return ["Quest", "Violet Gym"];
				case 8:		return ["Quest", "Violet Gym Rematch"];
				case 9:		return ["Quest", "Onix Trade"];
				case 10:	return ["Quest", "Sprout Tower"];
				case 11:	return ["Quest", "Sprout Tower Rematch"];
				case 12:	return ["Quest", "Mewthree Violet City"];
				case 13:	return ["Quest", "Mewthree Violet City Rematch"];
				case 14:	return ["Optional Quest", "Mareep Battle 1"];
				case 15:	return ["Optional Quest", "Wooper Battle 1"];
				case 16:	return ["Quest", "Rocket Fight"];
				case 17:	return ["Quest", "Unown Battle"];
				case 18:	return ["Item", "Metal Coat"];
				case 19:	return ["Quest", "Talked To Ash Ruins"];
				case 20:	return ["Quest", "Unown Entei Battle"];
				case 21:	return ["Quest", "Talked To Ash After Entei"];
				case 22:	return ["Quest", "Battled Magikarp Rocket"];
				case 23:	return ["Quest", "Taled To Ash Inside Ruins"];
				case 24:	return ["Quest", "Fisherman Qwalfish"];
				case 25:	return ["Quest", "Fisherman Tentacool"];
				case 26:	return ["Quest", "Fisherman Magikarp"];
				case 27:	return ["Quest", "Easter Bunny Hunt"];
				case 28:	return ["Quest", "Running Shoes"];
				case 29:	return ["Quest", "Main Quest"];
				case 30:	return ["Quest", "Left New Bark"];
				case 31:	return ["Quest", "Lass Route 29"];
				case 32:	return ["Quest", "Camper Route 46"];
				case 33:	return ["Side Quest", "Flowers"];
				case 34:	return ["Trainer", "Cherrygrove Kid"];
				case 35:	return ["Trainer", "Route 30 Youngster"];
				case 36:	return ["Trainer", "Route 30 Youngster 2"];
				case 37:	return ["Trainer", "Route 30 Bug Catcher"];
				case 38:	return ["Trainer", "Route 31 Bug Catcher"];
				case 39:	return ["Trainer", "Sprout Tower Monk 1"];
				case 40:	return ["Trainer", "Sprout Tower Monk 2"];
				case 41:	return ["Trainer", "Sprout Tower Monk 3"];
				case 42:	return ["Trainer", "Sprout Tower Elder"];
				case 43:	return ["Trainer", "Violet School Kid 1"];
				case 44:	return ["Trainer", "Violet School Kid 2"];
				case 45:	return ["Trainer", "Violet School Kid 3"];
				case 46:	return ["Trainer", "Violet Gym Man 1"];
				case 47:	return ["Trainer", "Violet Gym Man 2"];
				case 48:	return ["Trainer", "Violet Gym Falkner"];
				case 49:	return ["Trainer", "Route 32 North Camper"];
				case 50:	return ["Trainer", "Route 32 Middle Youngster"];
				case 51:	return ["Trainer", "Ruins Scientist"];
				case 52:	return ["Trainer", "Route 32 South Fisherman"];
				case 53:	return ["Trainer", "Union Cave 1 Hiker"];
				case 54:	return ["Trainer", "Union Cave 1 Camper"];
				case 55:	return ["Trainer", "Union Cave 2 Hiker"];
				case 56:	return ["Trainer", "Route 33 Hiker"];
				case 57:	return ["Trainer", "Azalea Gym Bug Catcher"];
				case 58:	return ["Trainer", "Azalea Gym Girls"];
				case 59:	return ["Trainer", "Azalea Gym Bugsy"];
				case 60:	return ["Trainer", "Azalea Town Man"];
				case 61:	return ["Trainer", "Ilex Forest Bug Catcher"];
				case 62:	return ["Main Quest", "2"];
				case 63:	return ["Trainer", "Route 34 Lass"];
				case 64:	return ["Main Quest", "3"];
				case 65:	return ["Item", "Shiny Stone"];
				case 66:	return ["Other", "Got Bike"];
				case 67:	return ["Other", "Game Corner Coins"];
				case 68:	return ["TM", "Blizzard"];
				case 69:	return ["TM", "Thunder"];
				case 70:	return ["TM", "Fire Blast"];
				case 71:	return ["TM", "Substitute"];
				case 72:	return ["TM", "Swords Dance"];
				case 73:	return ["TM", "Rest"];
				case 74:	return ["TM", "Flamethrower"];
				case 75:	return ["TM", "Ice Beam"];
				case 76:	return ["TM", "Thunderbolt"];
				case 77:	return ["TM", "Dragon Rage"];
				case 78:	return ["TM", "Hyper Beam"];
				case 79:	return ["TM", "Double Team"];
				case 80:	return ["TM", "Psychic"];
				case 81:	return ["TM", "Shadow Ball"];
				case 82:	return ["TM", "Iron Tail"];
				case 83:	return ["TM", "Endure"];
				case 84:	return ["TM", "Hidden Power"];
				case 85:	return ["TM", "Gyro Ball"];
				case 86:	return ["TM", "Giga Impact"];
				case 87:	return ["TM", "Flash"];
				case 88:	return ["TM", "Protect"];
				case 89:	return ["TM", "False Swipe"];
				case 90:	return ["TM", "Light Screen"];
				case 91:	return ["TM", "Reflect"];
				case 92:	return ["TM", "Solarbeam"];
				case 93:	return ["TM", "Focus Blast"];
				case 94:	return ["TM", "Thunder Punch"];
				case 95:	return ["TM", "Fire Punch"];
				case 96:	return ["TM", "Ice Punch"];
				case 97:	return ["TM", "Rock Smash"];
				case 98:	return ["Trainer", "Route 35 Bug Catcher"];
				case 99:	return ["Trainer", "National Park Bug Catcher"];
				case 100:	return ["Trainer", "Route 37 Joey"];
				case 101:	return ["TM", "Dark Pulse"];
				case 102:	return ["Trainer", "Route 38 Lass"];
				case 103:	return ["Trainer", "Route 39 Man"];
				case 104:	return ["Other", "Fish Super Rod"];
				case 105:	return ["Item", "Wave Incense"];
				case 106:	return ["Item", "Sea Incense"];
				case 107:	return ["Item", "Lax Incense"];
				case 108:	return ["Item", "Full Incense"];
				case 109:	return ["Item", "Luck Incense"];
				case 110:	return ["Item", "Odd Incense"];
				case 111:	return ["Item", "Rock Incense"];
				case 112:	return ["Item", "Rose Incense"];
				case 113:	return ["Item", "Upgrade"];
				case 114:	return ["Item", "Dubious Disc"];
				case 115:	return ["Item", "Electirizer"];
				case 116:	return ["Item", "Magmarizer"];
				case 117:	return ["Item", "Protector"];
				case 118:	return ["Item", "Oval Stone"];
				case 119:	return ["Item", "Razor Claw"];
				case 120:	return ["Item", "Razor Fang"];
				case 121:	return ["TM", "Dazzling Gleam"];
				case 122:	return ["Item", "Pure Incense"];
				case 2000:	return ["Temp Quest", "Mom Convo"];
				case 2001:	return ["Temp Quest", "Scientist Convo"];
				case 2002:	return ["Temp Quest", "Lady Mom Convo"];
				case 2003:	return ["Temp Quest", "First Time Outside House"];
				case 2004:	return ["Temp Quest", "First Time Inside Lab"];
				case 2005:	return ["Temp Quest", "Man Fat Convo"];
				case 2006:	return ["Temp Quest", "Your Poke Escape"];
				case 2007:	return ["Temp Quest", "Mom Convo"];
				case 2008:	return ["Temp Quest", "Elm Convo"];
				case 2009:	return ["Temp Quest", "Elm Convo"];
				case 2010:	return ["Temp Quest", "Mom Convo"];
				case 2011:	return ["Temp Quest", "Fist Time Outside"];
				case 2012:	return ["Temp Quest", "Rival Convo"];
				case 2013:	return ["Temp Quest", "Rival Convo"];
				case 2014:	return ["Temp Quest", "Elm Outside Convo"];
				case 2015:	return ["Temp Quest", "First Time Outside"];
				case 2016:	return ["Temp Quest", "Rival Convo"];
				case 2017:	return ["Temp Quest", "Mom Convo"];
				case 2018:	return ["Temp Quest", "Falkner Battle Attempted"];
				case 2019:	return ["Temp Quest", "Monk Convo"];
				case 2020:	return ["Temp Quest", "Mewthree Violet City Rematch Attempted"];
				case 2021:	return ["Temp Optional Quest", "Mareep Battle Attempted"];
				case 2022:	return ["Temp Optional Quest", "Wooper Battle Attempted"];
				case 2023:	return ["Temp Optional Quest", "Rocket Battle Attempted"];
				case 2024:	return ["Temp Quest", "Mewthree Route 32 Attempted"];
				case 2025:	return ["Temp Quest", "Mewthree Attempted Session"];
			}
			return ["Unknown", "Missing Info on Tag #" + tag];
		}
		
		public static function getExtraValues(tag:int):Array
		{
			switch(tag)
			{
				case 1:		return [[1, "Chikorita"], [2, "Cyndaquil"], [3, "Totodile"]];
				case 2:		return [[1, "Complete"]];
				case 3:		return [[1, "Complete"]];
				case 4:		return [[1, "Recieved"]];
				case 5:		return [[1, "Complete"]];
				case 6:		return [[1, "Entered"], [2, "Calmed Birds"], [3, "Mewthree"]];
				case 7:		return [[1, "Complete"]];
				case 8:		return [[1, "Complete"]];
				case 2018:	return [[1, "Flag Set"]];
				case 2019:	return [[1, "Talked to Monk"]];
				case 2020:	return [[1, "Flag Set"]];
			}
			return [];
		}
		
		public static const POKEMON_FUNC_NAME:String = "getPokemonName";
		public static const POKEMON_INDEX_START:int = 0;
		public static const POKEMON_INDEX_END:int = 719;
		public static function getPokemonName(num:int):String
		{
			switch(num)
			{
				case 0:		return "-";
				case 1:		return "Bulbasaur";
				case 2:		return "Ivysaur";
				case 3:		return "Venusaur";
				case 4:		return "Charmander";
				case 5:		return "Charmeleon";
				case 6:		return "Charizard";
				case 7:		return "Squirtle";
				case 8:		return "Wartortle";
				case 9:		return "Blastoise";
				case 10:	return "Caterpie";
				case 11:	return "Metapod";
				case 12:	return "Butterfree";
				case 13:	return "Weedle";
				case 14:	return "Kakuna";
				case 15:	return "Beedrill";
				case 16:	return "Pidgey";
				case 17:	return "Pidgeotto";
				case 18:	return "Pidgeot";
				case 19:	return "Rattata";
				case 20:	return "Raticate";
				case 21:	return "Spearow";
				case 22:	return "Fearow";
				case 23:	return "Ekans";
				case 24:	return "Arbok";
				case 25:	return "Pikachu";
				case 26:	return "Raichu";
				case 27:	return "Sandshrew";
				case 28:	return "Sandslash";
				case 29:	return "Nidoran (f)";
				case 30:	return "Nidorina";
				case 31:	return "Nidoqueen";
				case 32:	return "Nidoran (m)";
				case 33:	return "Nidorino";
				case 34:	return "Nidoking";
				case 35:	return "Clefairy";
				case 36:	return "Clefable";
				case 37:	return "Vulpix";
				case 38:	return "Ninetales";
				case 39:	return "Jigglypuff";
				case 40:	return "Wigglytuff";
				case 41:	return "Zubat";
				case 42:	return "Golbat";
				case 43:	return "Oddish";
				case 44:	return "Gloom";
				case 45:	return "Vileplume";
				case 46:	return "Paras";
				case 47:	return "Parasect";
				case 48:	return "Venonat";
				case 49:	return "Venomoth";
				case 50:	return "Diglett";
				case 51:	return "Dugtrio";
				case 52:	return "Meowth";
				case 53:	return "Persian";
				case 54:	return "Psyduck";
				case 55:	return "Golduck";
				case 56:	return "Mankey";
				case 57:	return "Primeape";
				case 58:	return "Growlithe";
				case 59:	return "Arcanine";
				case 60:	return "Poliwag";
				case 61:	return "Poliwhirl";
				case 62:	return "Poliwrath";
				case 63:	return "Abra";
				case 64:	return "Kadabra";
				case 65:	return "Alakazam";
				case 66:	return "Machop";
				case 67:	return "Machoke";
				case 68:	return "Machamp";
				case 69:	return "Bellsprout";
				case 70:	return "Weepinbell";
				case 71:	return "Victreebel";
				case 72:	return "Tentacool";
				case 73:	return "Tentacruel";
				case 74:	return "Geodude";
				case 75:	return "Graveler";
				case 76:	return "Golem";
				case 77:	return "Ponyta";
				case 78:	return "Rapidash";
				case 79:	return "Slowpoke";
				case 80:	return "Slowbro";
				case 81:	return "Magnemite";
				case 82:	return "Magneton";
				case 83:	return "Farfetch'd";
				case 84:	return "Doduo";
				case 85:	return "Dodrio";
				case 86:	return "Seel";
				case 87:	return "Dewgong";
				case 88:	return "Grimer";
				case 89:	return "Muk";
				case 90:	return "Shellder";
				case 91:	return "Cloyster";
				case 92:	return "Gastly";
				case 93:	return "Haunter";
				case 94:	return "Gengar";
				case 95:	return "Onix";
				case 96:	return "Drowzee";
				case 97:	return "Hypno";
				case 98:	return "Krabby";
				case 99:	return "Kingler";
				case 100:	return "Voltorb";
				case 101:	return "Electrode";
				case 102:	return "Exeggcute";
				case 103:	return "Exeggutor";
				case 104:	return "Cubone";
				case 105:	return "Marowak";
				case 106:	return "Hitmonlee";
				case 107:	return "Hitmonchan";
				case 108:	return "Lickitung";
				case 109:	return "Koffing";
				case 110:	return "Weezing";
				case 111:	return "Rhyhorn";
				case 112:	return "Rhydon";
				case 113:	return "Chansey";
				case 114:	return "Tangela";
				case 115:	return "Kangaskhan";
				case 116:	return "Horsea";
				case 117:	return "Seadra";
				case 118:	return "Goldeen";
				case 119:	return "Seaking";
				case 120:	return "Staryu";
				case 121:	return "Starmie";
				case 122:	return "Mr. Mime";
				case 123:	return "Scyther";
				case 124:	return "Jynx";
				case 125:	return "Electabuzz";
				case 126:	return "Magmar";
				case 127:	return "Pinsir";
				case 128:	return "Tauros";
				case 129:	return "Magikarp";
				case 130:	return "Gyarados";
				case 131:	return "Lapras";
				case 132:	return "Ditto";
				case 133:	return "Eevee";
				case 134:	return "Vaporeon";
				case 135:	return "Jolteon";
				case 136:	return "Flareon";
				case 137:	return "Porygon";
				case 138:	return "Omanyte";
				case 139:	return "Omastar";
				case 140:	return "Kabuto";
				case 141:	return "Kabutops";
				case 142:	return "Aerodactyl";
				case 143:	return "Snorlax";
				case 144:	return "Articuno";
				case 145:	return "Zapdos";
				case 146:	return "Moltres";
				case 147:	return "Dratini";
				case 148:	return "Dragonair";
				case 149:	return "Dragonite";
				case 150:	return "Mewtwo";
				case 151:	return "Mew";
				case 152:	return "Chikorita";
				case 153:	return "Bayleef";
				case 154:	return "Meganium";
				case 155:	return "Cyndaquil";
				case 156:	return "Quilava";
				case 157:	return "Typhlosion";
				case 158:	return "Totodile";
				case 159:	return "Croconaw";
				case 160:	return "Feraligatr";
				case 161:	return "Sentret";
				case 162:	return "Furret";
				case 163:	return "Hoothoot";
				case 164:	return "Noctowl";
				case 165:	return "Ledyba";
				case 166:	return "Ledian";
				case 167:	return "Spinarak";
				case 168:	return "Ariados";
				case 169:	return "Crobat";
				case 170:	return "Chinchou";
				case 171:	return "Lanturn";
				case 172:	return "Pichu";
				case 173:	return "Cleffa";
				case 174:	return "Igglybuff";
				case 175:	return "Togepi";
				case 176:	return "Togetic";
				case 177:	return "Natu";
				case 178:	return "Xatu";
				case 179:	return "Mareep";
				case 180:	return "Flaaffy";
				case 181:	return "Ampharos";
				case 182:	return "Bellossom";
				case 183:	return "Marill";
				case 184:	return "Azumarill";
				case 185:	return "Sudowoodo";
				case 186:	return "Politoed";
				case 187:	return "Hoppip";
				case 188:	return "Skiploom";
				case 189:	return "Jumpluff";
				case 190:	return "Aipom";
				case 191:	return "Sunkern";
				case 192:	return "Sunflora";
				case 193:	return "Yanma";
				case 194:	return "Wooper";
				case 195:	return "Quagsire";
				case 196:	return "Espeon";
				case 197:	return "Umbreon";
				case 198:	return "Murkrow";
				case 199:	return "Slowking";
				case 200:	return "Misdreavus";
				case 201:	return "Unown";
				case 202:	return "Wobbuffet";
				case 203:	return "Girafarig";
				case 204:	return "Pineco";
				case 205:	return "Forretress";
				case 206:	return "Dunsparce";
				case 207:	return "Gligar";
				case 208:	return "Steelix";
				case 209:	return "Snubbull";
				case 210:	return "Granbull";
				case 211:	return "Qwilfish";
				case 212:	return "Scizor";
				case 213:	return "Shuckle";
				case 214:	return "Heracross";
				case 215:	return "Sneasel";
				case 216:	return "Teddiursa";
				case 217:	return "Ursaring";
				case 218:	return "Slugma";
				case 219:	return "Magcargo";
				case 220:	return "Swinub";
				case 221:	return "Piloswine";
				case 222:	return "Corsola";
				case 223:	return "Remoraid";
				case 224:	return "Octillery";
				case 225:	return "Delibird";
				case 226:	return "Mantine";
				case 227:	return "Skarmory";
				case 228:	return "Houndour";
				case 229:	return "Houndoom";
				case 230:	return "Kingdra";
				case 231:	return "Phanpy";
				case 232:	return "Donphan";
				case 233:	return "Porygon2";
				case 234:	return "Stantler";
				case 235:	return "Smeargle";
				case 236:	return "Tyrogue";
				case 237:	return "Hitmontop";
				case 238:	return "Smoochum";
				case 239:	return "Elekid";
				case 240:	return "Magby";
				case 241:	return "Miltank";
				case 242:	return "Blissey";
				case 243:	return "Raikou";
				case 244:	return "Entei";
				case 245:	return "Suicune";
				case 246:	return "Larvitar";
				case 247:	return "Pupitar";
				case 248:	return "Tyranitar";
				case 249:	return "Lugia";
				case 250:	return "Ho-oh";
				case 251:	return "Celebi";
				case 252:	return "Treecko";
				case 253:	return "Grovyle";
				case 254:	return "Sceptile";
				case 255:	return "Torchic";
				case 256:	return "Combusken";
				case 257:	return "Blaziken";
				case 258:	return "Mudkip";
				case 259:	return "Marshtomp";
				case 260:	return "Swampert";
				case 261:	return "Poochyena";
				case 262:	return "Mightyena";
				case 263:	return "Zigzagoon";
				case 264:	return "Linoone";
				case 265:	return "Wurmple";
				case 266:	return "Silcoon";
				case 267:	return "Beautifly";
				case 268:	return "Cascoon";
				case 269:	return "Dustox";
				case 270:	return "Lotad";
				case 271:	return "Lombre";
				case 272:	return "Ludicolo";
				case 273:	return "Seedot";
				case 274:	return "Nuzleaf";
				case 275:	return "Shiftry";
				case 276:	return "Taillow";
				case 277:	return "Swellow";
				case 278:	return "Wingull";
				case 279:	return "Pelipper";
				case 280:	return "Ralts";
				case 281:	return "Kirlia";
				case 282:	return "Gardevoir";
				case 283:	return "Surskit";
				case 284:	return "Masquerain";
				case 285:	return "Shroomish";
				case 286:	return "Breloom";
				case 287:	return "Slakoth";
				case 288:	return "Vigoroth";
				case 289:	return "Slaking";
				case 290:	return "Nincada";
				case 291:	return "Ninjask";
				case 292:	return "Shedinja";
				case 293:	return "Whismur";
				case 294:	return "Loudred";
				case 295:	return "Exploud";
				case 296:	return "Makuhita";
				case 297:	return "Hariyama";
				case 298:	return "Azurill";
				case 299:	return "Nosepass";
				case 300:	return "Skitty";
				case 301:	return "Delcatty";
				case 302:	return "Sableye";
				case 303:	return "Mawile";
				case 304:	return "Aron";
				case 305:	return "Lairon";
				case 306:	return "Aggron";
				case 307:	return "Meditite";
				case 308:	return "Medicham";
				case 309:	return "Electrike";
				case 310:	return "Manectric";
				case 311:	return "Plusle";
				case 312:	return "Minun";
				case 313:	return "Volbeat";
				case 314:	return "Illumise";
				case 315:	return "Roselia";
				case 316:	return "Gulpin";
				case 317:	return "Swalot";
				case 318:	return "Carvanha";
				case 319:	return "Sharpedo";
				case 320:	return "Wailmer";
				case 321:	return "Wailord";
				case 322:	return "Numel";
				case 323:	return "Camerupt";
				case 324:	return "Torkoal";
				case 325:	return "Spoink";
				case 326:	return "Grumpig";
				case 327:	return "Spinda";
				case 328:	return "Trapinch";
				case 329:	return "Vibrava";
				case 330:	return "Flygon";
				case 331:	return "Cacnea";
				case 332:	return "Cacturne";
				case 333:	return "Swablu";
				case 334:	return "Altaria";
				case 335:	return "Zangoose";
				case 336:	return "Seviper";
				case 337:	return "Lunatone";
				case 338:	return "Solrock";
				case 339:	return "Barboach";
				case 340:	return "Whiscash";
				case 341:	return "Corphish";
				case 342:	return "Crawdaunt";
				case 343:	return "Baltoy";
				case 344:	return "Claydol";
				case 345:	return "Lileep";
				case 346:	return "Cradily";
				case 347:	return "Anorith";
				case 348:	return "Armaldo";
				case 349:	return "Feebas";
				case 350:	return "Milotic";
				case 351:	return "Castform";
				case 352:	return "Kecleon";
				case 353:	return "Shuppet";
				case 354:	return "Banette";
				case 355:	return "Duskull";
				case 356:	return "Dusclops";
				case 357:	return "Tropius";
				case 358:	return "Chimecho";
				case 359:	return "Absol";
				case 360:	return "Wynaut";
				case 361:	return "Snorunt";
				case 362:	return "Glalie";
				case 363:	return "Spheal";
				case 364:	return "Sealeo";
				case 365:	return "Walrein";
				case 366:	return "Clamperl";
				case 367:	return "Huntail";
				case 368:	return "Gorebyss";
				case 369:	return "Relicanth";
				case 370:	return "Luvdisc";
				case 371:	return "Bagon";
				case 372:	return "Shelgon";
				case 373:	return "Salamence";
				case 374:	return "Beldum";
				case 375:	return "Metang";
				case 376:	return "Metagross";
				case 377:	return "Regirock";
				case 378:	return "Regice";
				case 379:	return "Registeel";
				case 380:	return "Latias";
				case 381:	return "Latios";
				case 382:	return "Kyogre";
				case 383:	return "Groudon";
				case 384:	return "Rayquaza";
				case 385:	return "Jirachi";
				case 386:	return "Deoxys";
				case 387:	return "Turtwig";
				case 388:	return "Grotle";
				case 389:	return "Torterra";
				case 390:	return "Chimchar";
				case 391:	return "Monferno";
				case 392:	return "Infernape";
				case 393:	return "Piplup";
				case 394:	return "Prinplup";
				case 395:	return "Empoleon";
				case 396:	return "Starly";
				case 397:	return "Staravia";
				case 398:	return "Staraptor";
				case 399:	return "Bidoof";
				case 400:	return "Bibarel";
				case 401:	return "Kricketot";
				case 402:	return "Kricketune";
				case 403:	return "Shinx";
				case 404:	return "Luxio";
				case 405:	return "Luxray";
				case 406:	return "Budew";
				case 407:	return "Roserade";
				case 408:	return "Cranidos";
				case 409:	return "Rampardos";
				case 410:	return "Shieldon";
				case 411:	return "Bastiodon";
				case 412:	return "Burmy";
				case 413:	return "Wormadam";
				case 414:	return "Mothim";
				case 415:	return "Combee";
				case 416:	return "Vespiquen";
				case 417:	return "Pachirisu";
				case 418:	return "Buizel";
				case 419:	return "Floatzel";
				case 420:	return "Cherubi";
				case 421:	return "Cherrim";
				case 422:	return "Shellos";
				case 423:	return "Gastrodon";
				case 424:	return "Ambipom";
				case 425:	return "Drifloon";
				case 426:	return "Drifblim";
				case 427:	return "Buneary";
				case 428:	return "Lopunny";
				case 429:	return "Mismagius";
				case 430:	return "Honchkrow";
				case 431:	return "Glameow";
				case 432:	return "Purugly";
				case 433:	return "Chingling";
				case 434:	return "Stunky";
				case 435:	return "Skuntank";
				case 436:	return "Bronzor";
				case 437:	return "Bronzong";
				case 438:	return "Bonsly";
				case 439:	return "Mime Jr.";
				case 440:	return "Happiny";
				case 441:	return "Chatot";
				case 442:	return "Spiritomb";
				case 443:	return "Gible";
				case 444:	return "Gabite";
				case 445:	return "Garchomp";
				case 446:	return "Munchlax";
				case 447:	return "Riolu";
				case 448:	return "Lucario";
				case 449:	return "Hippopotas";
				case 450:	return "Hippowdon";
				case 451:	return "Skorupi";
				case 452:	return "Drapion";
				case 453:	return "Croagunk";
				case 454:	return "Toxicroak";
				case 455:	return "Carnivine";
				case 456:	return "Finneon";
				case 457:	return "Lumineon";
				case 458:	return "Mantyke";
				case 459:	return "Snover";
				case 460:	return "Abomasnow";
				case 461:	return "Weavile";
				case 462:	return "Magnezone";
				case 463:	return "Lickilicky";
				case 464:	return "Rhyperior";
				case 465:	return "Tangrowth";
				case 466:	return "Electivire";
				case 467:	return "Magmortar";
				case 468:	return "Togekiss";
				case 469:	return "Yanmega";
				case 470:	return "Leafeon";
				case 471:	return "Glaceon";
				case 472:	return "Gliscor";
				case 473:	return "Mamoswine";
				case 474:	return "Porygon-Z";
				case 475:	return "Gallade";
				case 476:	return "Probopass";
				case 477:	return "Dusknoir";
				case 478:	return "Froslass";
				case 479:	return "Rotom";
				case 480:	return "Uxie";
				case 481:	return "Mesprit";
				case 482:	return "Azelf";
				case 483:	return "Dialga";
				case 484:	return "Palkia";
				case 485:	return "Heatran";
				case 486:	return "Regigigas";
				case 487:	return "Giratina";
				case 488:	return "Cresselia";
				case 489:	return "Phione";
				case 490:	return "Manaphy";
				case 491:	return "Darkrai";
				case 492:	return "Shaymin";
				case 493:	return "Arceus";
				case 494:	return "Victini";
				case 495:	return "Snivy";
				case 496:	return "Servine";
				case 497:	return "Serperior";
				case 498:	return "Tepig";
				case 499:	return "Pignite";
				case 500:	return "Emboar";
				case 501:	return "Oshawott";
				case 502:	return "Dewott";
				case 503:	return "Samurott";
				case 504:	return "Patrat";
				case 505:	return "Watchog";
				case 506:	return "Lillipup";
				case 507:	return "Herdier";
				case 508:	return "Stoutland";
				case 509:	return "Purrloin";
				case 510:	return "Liepard";
				case 511:	return "Pansage";
				case 512:	return "Simisage";
				case 513:	return "Pansear";
				case 514:	return "Simisear";
				case 515:	return "Panpour";
				case 516:	return "Simipour";
				case 517:	return "Munna";
				case 518:	return "Musharna";
				case 519:	return "Pidove";
				case 520:	return "Tranquill";
				case 521:	return "Unfezant";
				case 522:	return "Blitzle";
				case 523:	return "Zebstrika";
				case 524:	return "Roggenrola";
				case 525:	return "Boldore";
				case 526:	return "Gigalith";
				case 527:	return "Woobat";
				case 528:	return "Swoobat";
				case 529:	return "Drilbur";
				case 530:	return "Excadrill";
				case 531:	return "Audino";
				case 532:	return "Timburr";
				case 533:	return "Gurdurr";
				case 534:	return "Conkeldurr";
				case 535:	return "Tympole";
				case 536:	return "Palpitoad";
				case 537:	return "Seismitoad";
				case 538:	return "Throh";
				case 539:	return "Sawk";
				case 540:	return "Sewaddle";
				case 541:	return "Swadloon";
				case 542:	return "Leavanny";
				case 543:	return "Venipede";
				case 544:	return "Whirlipede";
				case 545:	return "Scolipede";
				case 546:	return "Cottonee";
				case 547:	return "Whimsicott";
				case 548:	return "Petilil";
				case 549:	return "Lilligant";
				case 550:	return "Basculin";
				case 551:	return "Sandile";
				case 552:	return "Krokorok";
				case 553:	return "Krookodile";
				case 554:	return "Darumaka";
				case 555:	return "Darmanitan";
				case 556:	return "Maractus";
				case 557:	return "Dwebble";
				case 558:	return "Crustle";
				case 559:	return "Scraggy";
				case 560:	return "Scrafty";
				case 561:	return "Sigilyph";
				case 562:	return "Yamask";
				case 563:	return "Cofagrigus";
				case 564:	return "Tirtouga";
				case 565:	return "Carracosta";
				case 566:	return "Archen";
				case 567:	return "Archeops";
				case 568:	return "Trubbish";
				case 569:	return "Garbodor";
				case 570:	return "Zorua";
				case 571:	return "Zoroark";
				case 572:	return "Minccino";
				case 573:	return "Cinccino";
				case 574:	return "Gothita";
				case 575:	return "Gothorita";
				case 576:	return "Gothitelle";
				case 577:	return "Solosis";
				case 578:	return "Duosion";
				case 579:	return "Reuniclus";
				case 580:	return "Ducklett";
				case 581:	return "Swanna";
				case 582:	return "Vanillite";
				case 583:	return "Vanillish";
				case 584:	return "Vanilluxe";
				case 585:	return "Deerling";
				case 586:	return "Sawsbuck";
				case 587:	return "Emolga";
				case 588:	return "Karrablast";
				case 589:	return "Escavalier";
				case 590:	return "Foongus";
				case 591:	return "Amoonguss";
				case 592:	return "Frillish";
				case 593:	return "Jellicent";
				case 594:	return "Alomomola";
				case 595:	return "Joltik";
				case 596:	return "Galvantula";
				case 597:	return "Ferroseed";
				case 598:	return "Ferrothorn";
				case 599:	return "Klink";
				case 600:	return "Klang";
				case 601:	return "Klinklang";
				case 602:	return "Tynamo";
				case 603:	return "Eelektrik";
				case 604:	return "Eelektross";
				case 605:	return "Elgyem";
				case 606:	return "Beheeyem";
				case 607:	return "Litwick";
				case 608:	return "Lampent";
				case 609:	return "Chandelure";
				case 610:	return "Axew";
				case 611:	return "Fraxure";
				case 612:	return "Haxorus";
				case 613:	return "Cubchoo";
				case 614:	return "Beartic";
				case 615:	return "Cryogonal";
				case 616:	return "Shelmet";
				case 617:	return "Accelgor";
				case 618:	return "Stunfisk";
				case 619:	return "Mienfoo";
				case 620:	return "Mienshao";
				case 621:	return "Druddigon";
				case 622:	return "Golett";
				case 623:	return "Golurk";
				case 624:	return "Pawniard";
				case 625:	return "Bisharp";
				case 626:	return "Bouffalant";
				case 627:	return "Rufflet";
				case 628:	return "Braviary";
				case 629:	return "Vullaby";
				case 630:	return "Mandibuzz";
				case 631:	return "Heatmor";
				case 632:	return "Durant";
				case 633:	return "Deino";
				case 634:	return "Zweilous";
				case 635:	return "Hydreigon";
				case 636:	return "Larvesta";
				case 637:	return "Volcarona";
				case 638:	return "Cobalion";
				case 639:	return "Terrakion";
				case 640:	return "Virizion";
				case 641:	return "Tornadus";
				case 642:	return "Thundurus";
				case 643:	return "Reshiram";
				case 644:	return "Zekrom";
				case 645:	return "Landorus";
				case 646:	return "Kyurem";
				case 647:	return "Keldeo";
				case 648:	return "Meloetta";
				case 649:	return "Genesect";
				case 650: 	return "Chespin";
				case 651: 	return "Quilladin";
				case 652: 	return "Chesnaught";
				case 653: 	return "Fennekin";
				case 654: 	return "Braixen";
				case 655: 	return "Delphox";
				case 656: 	return "Froakie";
				case 657: 	return "Frogadier";
				case 658: 	return "Greninja";
				case 659: 	return "Bunnelby";
				case 660: 	return "Diggersby";
				case 661: 	return "Fletchling";
				case 662: 	return "Fletchinder";
				case 663: 	return "Talonflame";
				case 664: 	return "Scatterbug";
				case 665: 	return "Spewpa";
				case 666: 	return "Vivillon";
				case 667: 	return "Litleo";
				case 668: 	return "Pyroar";
				case 669: 	return "Flabébé";
				case 670: 	return "Floette";
				case 671: 	return "Florges";
				case 672: 	return "Skiddo";
				case 673: 	return "Gogoat";
				case 674: 	return "Pancham";
				case 675: 	return "Pangoro";
				case 676: 	return "Furfrou";
				case 677: 	return "Espurr";
				case 678: 	return "Meowstic";
				case 679: 	return "Honedge";
				case 680: 	return "Doublade";
				case 681: 	return "Aegislash";
				case 682: 	return "Spritzee";
				case 683: 	return "Aromatisse";
				case 684: 	return "Swirlix";
				case 685: 	return "Slurpuff";
				case 686: 	return "Inkay";
				case 687: 	return "Malamar";
				case 688: 	return "Binacle";
				case 689: 	return "Barbaracle";
				case 690: 	return "Skrelp";
				case 691: 	return "Dragalge";
				case 692: 	return "Clauncher";
				case 693: 	return "Clawitzer";
				case 694: 	return "Helioptile";
				case 695: 	return "Heliolisk";
				case 696: 	return "Tyrunt";
				case 697: 	return "Tyrantrum";
				case 698: 	return "Amaura";
				case 699: 	return "Aurorus";
				case 700: 	return "Sylveon";
				case 701: 	return "Hawlucha";
				case 702: 	return "Dedenne";
				case 703: 	return "Carbink";
				case 704: 	return "Goomy";
				case 705: 	return "Sliggoo";
				case 706: 	return "Goodra";
				case 707: 	return "Klefki";
				case 708: 	return "Phantump";
				case 709: 	return "Trevenant";
				case 710: 	return "Pumpkaboo";
				case 711: 	return "Gourgeist";
				case 712: 	return "Bergmite";
				case 713: 	return "Avalugg";
				case 714: 	return "Noibat";
				case 715: 	return "Noivern";
				case 716: 	return "Xerneas";
				case 717: 	return "Yveltal";
				case 718: 	return "Zygarde";
				case 719: 	return "Diancie";
			}
			return "Pokemon #" + num.toString();
		}
		
		public static const MOVES_FUNC_NAME:String = "getMoveName";
		public static const MOVES_INDEX_START:int = 0;
		public static const MOVES_INDEX_END:int = 638;
		public static function getMoveName(num:int):String
		{
			switch(num)
			{
				case 0:		return "-";
				case 1:		return "Tackle";
				case 2:		return "Sand Attack";
				case 3:		return "Tail Whip";
				case 4:		return "Quick Attack";
				case 5:		return "Growl";
				case 6:		return "Scratch";
				case 7:		return "String Shot";
				case 8:		return "Poison Sting";
				case 9:		return "Leech Seed";
				case 10:	return "Ember";
				case 11:	return "Bubble";
				case 12:	return "Focus Energy";
				case 13:	return "Bug Bite";
				case 14:	return "Harden";
				case 15:	return "Gust";
				case 16:	return "Vine Whip";
				case 17:	return "Smokescreen";
				case 18:	return "Withdraw";
				case 19:	return "Bite";
				case 20:	return "Confusion";
				case 21:	return "Fury Attack";
				case 22:	return "Thundershock";
				case 23:	return "Thunderwave";
				case 24:	return "Poison Powder";
				case 25:	return "Defense Curl";
				case 26:	return "Sleep Powder";
				case 27:	return "Take Down";
				case 28:	return "Razor Leaf";
				case 29:	return "Dragon Rage";
				case 30:	return "Scary Face";
				case 31:	return "Water Gun";
				case 32:	return "Rapid Spin";
				case 33:	return "Pursuit";
				case 34:	return "Hyper Fang";
				case 35:	return "Sucker Punch";
				case 36:	return "Whirlwind";
				case 37:	return "Stun Spore";
				case 38:	return "Supersonic";
				case 39:	return "Twineedle";
				case 40:	return "Rage";
				case 41:	return "Electro Ball";
				case 42:	return "Peck";
				case 43:	return "Leer";
				case 44:	return "Aerial Ace";
				case 45:	return "Double Kick";
				case 46:	return "Fury Swipes";
				case 47:	return "Sing";
				case 48:	return "Pound";
				case 49:	return "Disable";
				case 50:	return "Round";
				case 51:	return "Low Kick";
				case 52:	return "Karate Chop";
				case 53:	return "Seismic Toss";
				case 54:	return "Leech Life";
				case 55:	return "Fury Cutter";
				case 56:	return "Transform";
				case 57:	return "Reflect Type";
				case 58:	return "Metronome";
				case 59:	return "Mega Punch";
				case 60:	return "Encore";
				case 61:	return "Double Slap";
				case 62:	return "Follow Me";
				case 63:	return "Minimize";
				case 64:	return "Mud Sport";
				case 65:	return "Rock Polish";
				case 66:	return "Rock Throw";
				case 67:	return "Magnitude";
				case 68:	return "Rollout";
				case 69:	return "Swift";
				case 70:	return "Wrap";
				case 71:	return "Glare";
				case 72:	return "Screech";
				case 73:	return "Acid";
				case 74:	return "Astonish";
				case 75:	return "Wing Attack";
				case 76:	return "Sweet Scent";
				case 77:	return "Twister";
				case 78:	return "Mirror Move";
				case 79:	return "Double Team";
				case 80:	return "Horn Attack";
				case 81:	return "Confuse Ray";
				case 82:	return "Rock Blast";
				case 83:	return "Protect";
				case 84:	return "Crunch";
				case 85:	return "Crush Claw";
				case 86:	return "Wake Up Slap";
				case 87:	return "Spore";
				case 88:	return "Chip Away";
				case 89:	return "Psybeam";
				case 90:	return "Smack Down";
				case 91:	return "Growth";
				case 92:	return "Fire Fang";
				case 93:	return "Water Pulse";
				case 94:	return "Toxic Spikes";
				case 95:	return "Featherdance";
				case 96:	return "Assurance";
				case 97:	return "Agility";
				case 98:	return "Stockpile";
				case 99:	return "Helping Hand";
				case 100:	return "Air Cutter";
				case 101:	return "Roar";
				case 102:	return "Odor Sleuth";
				case 103:	return "Flame Wheel";
				case 104:	return "Reversal";
				case 105:	return "Fire Spin";
				case 106:	return "Flame Burst";
				case 107:	return "Absorb";
				case 108:	return "Mega Drain";
				case 109:	return "Water Sport";
				case 110:	return "Hypnosis";
				case 111:	return "Rain Dance";
				case 112:	return "Bubblebeam";
				case 113:	return "Lucky Chant";
				case 114:	return "Body Slam";
				case 115:	return "Recover";
				case 116:	return "Teleport";
				case 117:	return "Miracle Eye";
				case 118:	return "Ally Switch";
				case 119:	return "Lick";
				case 120:	return "Lovely Kiss";
				case 121:	return "Powder Snow";
				case 122:	return "Ice Punch";
				case 123:	return "Heart Stamp";
				case 124:	return "Swallow";
				case 125:	return "Slam";
				case 126:	return "Spit Up";
				case 127:	return "Double Edge";
				case 128:	return "Sand Tomb";
				case 129:	return "Safeguard";
				case 130:	return "Slash";
				case 131:	return "Knock Off";
				case 132:	return "Leaf Tornado";
				case 133:	return "Aqua Tail";
				case 134:	return "Silver Wind";
				case 135:	return "Pin Missile";
				case 136:	return "Super Fang";
				case 137:	return "Acid Spray";
				case 138:	return "Cosmic Power";
				case 139:	return "Mud Shot";
				case 140:	return "Fake Tears";
				case 141:	return "Splash";
				case 142:	return "Thunderbolt";
				case 143:	return "Rest";
				case 144:	return "Selfdestruct";
				case 145:	return "Tailwind";
				case 146:	return "Reflect";
				case 147:	return "Flail";
				case 148:	return "Psychic";
				case 149:	return "Worry Seed";
				case 150:	return "Skull Bash";
				case 151:	return "Will O Wisp";
				case 152:	return "Belly Drum";
				case 153:	return "Petal Dance";
				case 154:	return "Dynamicpunch";
				case 155:	return "Bulldoze";
				case 156:	return "Ice Fang";
				case 157:	return "Synthesis";
				case 158:	return "Roost";
				case 159:	return "Mud Bomb";
				case 160:	return "Gyro Ball";
				case 161:	return "Flatter";
				case 162:	return "Acrobatics";
				case 163:	return "Moonlight";
				case 164:	return "Swagger";
				case 165:	return "Iron Defense";
				case 166:	return "Rage Powder";
				case 167:	return "Endeavor";
				case 168:	return "Feint";
				case 169:	return "Payback";
				case 170:	return "Telekinesis";
				case 171:	return "Thrash";
				case 172:	return "Gastro Acid";
				case 173:	return "Stealth Rock";
				case 174:	return "Rest Kyogre";
				case 175:	return "Fake Out";
				case 176:	return "Faint Attack";
				case 177:	return "Taunt";
				case 178:	return "Pay Day";
				case 179:	return "Power Gem";
				case 180:	return "Swords Dance";
				case 181:	return "Night Slash";
				case 182:	return "Poison Jab";
				case 183:	return "Seed Bomb";
				case 184:	return "Flamethrower";
				case 185:	return "Drill Peck";
				case 186:	return "Sandstorm";
				case 187:	return "Gravity";
				case 188:	return "Poison Fang";
				case 189:	return "Giga Drain";
				case 190:	return "Cross Chop";
				case 191:	return "Nasty Plot";
				case 192:	return "Extremespeed";
				case 193:	return "Hydro Pump";
				case 194:	return "Earthquake";
				case 195:	return "Avalanche";
				case 196:	return "Psycho Cut";
				case 197:	return "Barrier";
				case 198:	return "Bind";
				case 199:	return "Rock Tomb";
				case 200:	return "Camouflage";
				case 201:	return "Constrict";
				case 202:	return "Thunder";
				case 203:	return "Fire Blast";
				case 204:	return "Blizzard";
				case 205:	return "Magnitude 2";
				case 206:	return "Earth Power";
				case 207:	return "Dig";
				case 208:	return "Poison Gas";
				case 209:	return "Meditate";
				case 210:	return "Psych Up";
				case 211:	return "Synchronoise";
				case 212:	return "Light Screen";
				case 213:	return "Substitute";
				case 214:	return "Mimic";
				case 215:	return "Copycat";
				case 216:	return "Headbutt";
				case 217:	return "Mud Slap";
				case 218:	return "Bug Buzz";
				case 219:	return "Discharge";
				case 220:	return "Calm Mind";
				case 221:	return "Haze";
				case 222:	return "Dragonbreath";
				case 223:	return "Zen Headbutt";
				case 224:	return "Cut";
				case 225:	return "Flash";
				case 226:	return "Low Sweep";
				case 227:	return "Foresight";
				case 228:	return "Revenge";
				case 229:	return "Vital Throw";
				case 230:	return "Submission";
				case 231:	return "Sonicboom";
				case 232:	return "Spark";
				case 233:	return "Charge Beam";
				case 234:	return "Magnet Rise";
				case 235:	return "Aromatherapy";
				case 236:	return "Mind Reader";
				case 237:	return "Hex";
				case 238:	return "Explosion";
				case 239:	return "Stored Power";
				case 240:	return "Solarbeam";
				case 241:	return "Coil";
				case 242:	return "Inferno";
				case 243:	return "Dragon Dance";
				case 244:	return "Dragon Claw";
				case 245:	return "Shadow Claw";
				case 246:	return "Air Slash";
				case 247:	return "Flash Cannon";
				case 248:	return "Pluck";
				case 249:	return "Thunder Fang";
				case 250:	return "Cross Poison";
				case 251:	return "Tri Attack";
				case 252:	return "Kinesis";
				case 253:	return "Wide Guard";
				case 254:	return "Nightmare";
				case 255:	return "Magical Leaf";
				case 256:	return "Quick Guard";
				case 257:	return "Charge";
				case 258:	return "Guard Swap";
				case 259:	return "Power Swap";
				case 260:	return "Aurora Beam";
				case 261:	return "Aqua Ring";
				case 262:	return "Baton Pass";
				case 263:	return "Conversion";
				case 264:	return "Conversion 2";
				case 265:	return "Signal Beam";
				case 266:	return "Vacuum Wave";
				case 267:	return "Razor Wind";
				case 268:	return "X Scissor";
				case 269:	return "Vicegrip";
				case 270:	return "Brick Break";
				case 271:	return "Dragon Tail";
				case 272:	return "Dragon Rush";
				case 273:	return "False Swipe";
				case 274:	return "Celebi Heal";
				case 275:	return "Horn Drill";
				case 276:	return "Fissure";
				case 277:	return "Punishment";
				case 278:	return "Lock On";
				case 279:	return "Quiver Dance";
				case 280:	return "Curse";
				case 281:	return "Hyper Beam";
				case 282:	return "Leaf Storm";
				case 283:	return "Wring Out";
				case 284:	return "Guillotine";
				case 285:	return "Leaf Blade";
				case 286:	return "Future Sight";
				case 287:	return "Retaliate";
				case 288:	return "Gunk Shot";
				case 289:	return "Iron Tail";
				case 290:	return "Close Combat";
				case 291:	return "Hyper Voice";
				case 292:	return "Healing Wish";
				case 293:	return "Double Hit";
				case 294:	return "Mirror Coat";
				case 295:	return "Last Resort";
				case 296:	return "Ancientpower";
				case 297:	return "Stone Edge";
				case 298:	return "Sludge Wave";
				case 299:	return "Metal Sound";
				case 300:	return "Magnet Bomb";
				case 301:	return "Mirror Shot";
				case 302:	return "Extrasensory";
				case 303:	return "Heat Wave";
				case 304:	return "After You";
				case 305:	return "Superpower";
				case 306:	return "Steamroller";
				case 307:	return "Night Shade";
				case 308:	return "Shadow Ball";
				case 309:	return "Dream Eater";
				case 310:	return "Dark Pulse";
				case 311:	return "Destiny Bond";
				case 312:	return "Bone Club";
				case 313:	return "Bonemerang";
				case 314:	return "Bone Rush";
				case 315:	return "Shadow Punch";
				case 316:	return "Thunderpunch";
				case 317:	return "Fire Punch";
				case 318:	return "Hurricane";
				case 319:	return "Drill Run";
				case 320:	return "Final Gambit";
				case 321:	return "Circle Throw";
				case 322:	return "Meteor Mash";
				case 323:	return "Brave Bird";
				case 324:	return "Perish Song";
				case 325:	return "Outrage";
				case 326:	return "Metal Claw";
				case 327:	return "Stomp";
				case 328:	return "Brine";
				case 329:	return "Crabhammer";
				case 330:	return "Flare Blitz";
				case 331:	return "Magic Coat";
				case 332:	return "Psyshock";
				case 333:	return "Trump Card";
				case 334:	return "Smog";
				case 335:	return "Megahorn";
				case 336:	return "Zap Cannon";
				case 337:	return "Amnesia";
				case 338:	return "Waterfall";
				case 339:	return "Soak";
				case 340:	return "Yawn";
				case 341:	return "Snore";
				case 342:	return "Sleep Talk";
				case 343:	return "Heavy Slam";
				case 344:	return "Giga Impact";
				case 345:	return "Ice Shard";
				case 346:	return "Ice Beam";
				case 347:	return "Sheer Cold";
				case 348:	return "Acid Armor";
				case 349:	return "Dragon Pulse";
				case 350:	return "Me First";
				case 351:	return "Lava Plume";
				case 352:	return "Searing Shot";
				case 353:	return "Incinerate";
				case 354:	return "Endure";
				case 355:	return "Flame Charge";
				case 356:	return "Rolling Kick";
				case 357:	return "Hi Jump Kick";
				case 358:	return "Jump Kick";
				case 359:	return "Blaze Kick";
				case 360:	return "Mega Kick";
				case 361:	return "Comet Punch";
				case 362:	return "Mach Punch";
				case 363:	return "Bullet Punch";
				case 364:	return "Sky Uppercut";
				case 365:	return "Detect";
				case 366:	return "Counter";
				case 367:	return "Focus Punch";
				case 368:	return "Shadow Rush";
				case 369:	return "Icicle Spear";
				case 370:	return "Clamp";
				case 371:	return "Razor Shell";
				case 372:	return "Whirlpool";
				case 373:	return "Shell Smash";
				case 374:	return "Spike Cannon";
				case 375:	return "Spikes";
				case 376:	return "Icicle Crash";
				case 377:	return "Wonder Room";
				case 378:	return "Aqua Jet";
				case 379:	return "Muddy Water";
				case 380:	return "Muks Gas";
				case 381:	return "Sludge";
				case 382:	return "Sludge Bomb";
				case 383:	return "Uproar";
				case 384:	return "Acupressure";
				case 385:	return "Slack Off";
				case 386:	return "Heal Pulse";
				case 387:	return "Memento";
				case 388:	return "Wood Hammer";
				case 389:	return "Egg Bomb";
				case 390:	return "Bullet Seed";
				case 391:	return "Barrage";
				case 392:	return "Softboiled";
				case 393:	return "Refresh";
				case 394:	return "Hammer Arm";
				case 395:	return "Dizzy Punch";
				case 396:	return "Work Up";
				case 397:	return "Joeys Rock";
				case 398:	return "Joeys Bait";
				case 399:	return "Power Whip";
				case 400:	return "Tickle";
				case 401:	return "Ingrain";
				case 402:	return "Eruption";
				case 403:	return "Bounce";
				case 404:	return "Gary Potion";
				case 405:	return "Zapdos Drill Peck";
				case 406:	return "Zapdos Thunder";
				case 407:	return "Icy Wind";
				case 408:	return "Dive";
				case 409:	return "Hail";
				case 410:	return "Clear Smog";
				case 411:	return "Sunny Day";
				case 412:	return "Sky Drop";
				case 413:	return "Iron Head";
				case 414:	return "Rock Slide";
				case 415:	return "Toxic";
				case 416:	return "Shock Wave";
				case 417:	return "Aura Sphere";
				case 418:	return "Overheat";
				case 419:	return "V Create";
				case 420:	return "Fusion Bolt";
				case 421:	return "Fusion Flare";
				case 422:	return "Sky Attack";
				case 423:	return "Sharpen";
				case 424:	return "Psystrike";
				case 425:	return "Surf";
				case 426:	return "Strength";
				case 427:	return "Fly";
				case 428:	return "Freeze All Towers";
				case 429:	return "Slippery Floor";
				case 430:	return "Brain Freeze";
				case 431:	return "Anti Poison";
				case 432:	return "Tower Teleport";
				case 433:	return "Return To Pokeball";
				case 434:	return "Natural Gift";
				case 435:	return "Echoed Voice";
				case 436:	return "Psycho Shift";
				case 437:	return "Onix Boulder Throw";
				case 438:	return "Foul Play";
				case 439:	return "Torment";
				case 440:	return "Embargo";
				case 441:	return "Imprison";
				case 442:	return "Night Daze";
				case 443:	return "U Turn";
				case 444:	return "Hone Claws";
				case 445:	return "Cotton Spore";
				case 446:	return "Zai Potion";
				case 447:	return "Zapdos Weak Thundershock";
				case 448:	return "Zai Potion 2";
				case 449:	return "Force Palm";
				case 450:	return "Shadow Sneak";
				case 451:	return "Spider Web";
				case 452:	return "Mist";
				case 453:	return "Weather Ball";
				case 454:	return "Mean Look";
				case 455:	return "Spite";
				case 456:	return "Charm";
				case 457:	return "Wild Charge";
				case 458:	return "Pidgey Sand Attack";
				case 459:	return "Pidgeotto Gust";
				case 460:	return "Pidgeot Gust";
				case 461:	return "Cotton Guard";
				case 462:	return "Wish";
				case 463:	return "Doom Desire";
				case 464:	return "Sweet Kiss";
				case 465:	return "Facade";
				case 466:	return "Pidgey Gust 2";
				case 467:	return "Pidgeotto Gust 2";
				case 468:	return "Pidgeot Gust 2";
				case 469:	return "Bellsprout Wrap";
				case 470:	return "Bellsprout Razor Leaf";
				case 471:	return "Energy Ball";
				case 472:	return "Weak Gust";
				case 473:	return "Lugia Gust";
				case 474:	return "Zai Potion 3";
				case 475:	return "Lugia Gust 2";
				case 476:	return "Venoshock";
				case 477:	return "Head Smash";
				case 478:	return "Bide";
				case 479:	return "Struggle Bug";
				case 480:	return "Hidden Power";
				case 481:	return "Attract";
				case 482:	return "Captivate";
				case 483:	return "Dual Chop";
				case 484:	return "Pain Split";
				case 485:	return "Autotomize";
				case 486:	return "Metal Burst";
				case 487:	return "Ice Ball";
				case 488:	return "Entei Fireball";
				case 489:	return "Ominous Wind";
				case 490:	return "Rock Climb";
				case 491:	return "Morning Sun";
				case 492:	return "Bestow";
				case 493:	return "Fling";
				case 494:	return "Frustration";
				case 495:	return "Return 1";
				case 496:	return "Magma Storm";
				case 497:	return "Entrainment";
				case 498:	return "Psywave";
				case 499:	return "Snatch";
				case 500:	return "Skill Swap";
				case 501:	return "Heal Block";
				case 502:	return "Trick";
				case 503:	return "Switcheroo";
				case 504:	return "Covet";
				case 505:	return "Grudge";
				case 506:	return "Role Play";
				case 507:	return "Bulk Up";
				case 508:	return "Drain Punch";
				case 509:	return "Mewthree Attack";
				case 510:	return "Shadow Blitz";
				case 511:	return "Shadow Wave";
				case 512:	return "Heal Bell";
				case 513:	return "Block";
				case 514:	return "Poison Tail";
				case 515:	return "Ariados Spider Web";
				case 516:	return "Spinarak Bug Bite";
				case 517:	return "Defend Order";
				case 518:	return "Heal Order";
				case 519:	return "Attack Order";
				case 520:	return "Simple Beam";
				case 521:	return "Guard Split";
				case 522:	return "Power Split";
				case 523:	return "Heat Crash";
				case 524:	return "Arm Thrust";
				case 525:	return "Magic Room";
				case 526:	return "Howl";
				case 527:	return "Recycle";
				case 528:	return "Triple Kick";
				case 529:	return "Miltank Rollout";
				case 530:	return "Miltank Body Slam";
				case 531:	return "Miltank Milk Drink";
				case 532:	return "Temp Attack";
				case 533:	return "Miltank Defense Curl";
				case 534:	return "Gear Grind";
				case 535:	return "Shift Gear";
				case 536:	return "Grasswhistle";
				case 537:	return "Quash";
				case 538:	return "Beat Up";
				case 539:	return "Rock Smash";
				case 540:	return "Smelling Salt";
				case 541:	return "Volt Switch";
				case 542:	return "Defog";
				case 543:	return "Rock Wrecker";
				case 544:	return "Houndoom Flamethrower";
				case 545:	return "Focus Blast";
				case 546:	return "Fiery Dance";
				case 547:	return "Head Charge";
				case 548:	return "Milk Drink";
				case 549:	return "Geomancy";
				case 550:	return "Moonblast";
				case 551:	return "Mysty Terrain";
				case 552:	return "Horn Leech";
				case 553:	return "Nature Power";
				case 554:	return "Snarl";
				case 555:	return "Oblivion Wing";
				case 556:	return "Phantom Force";
				case 557:	return "Glaciate";
				case 558:	return "Hitmonchan Punch";
				case 559:	return "Steelix Rock Slide";
				case 560:	return "Sketch";
				case 561:	return "Water Spout";
				case 562:	return "Present";
				case 563:	return "Octazooka";
				case 564:	return "Steel Wing";
				case 565:	return "Disarming Voice";
				case 566:	return "Forest Curse";
				case 567:	return "Generator Electric";
				case 568:	return "Massive Roar";
				case 569:	return "Blinding Flash";
				case 570:	return "Machine Takeover";
				case 571:	return "Massive Explode";
				case 572:	return "Magnetic Pull";
				case 573:	return "Agility Discharge";
				case 574:	return "Power Trick";
				case 575:	return "Sacred Sword";
				case 576:	return "Kings Shield";
				case 577:	return "Fairy Lock";
				case 578:	return "Fairy Wind";
				case 579:	return "Draining Kiss";
				case 580:	return "Crafty Shield";
				case 581:	return "Play Rough";
				case 582:	return "Onix Tunnel";
				case 583:	return "Tunnel Magic";
				case 584:	return "Sudowoodo Trick";
				case 585:	return "Dark Void";
				case 586:	return "Life Beam";
				case 587:	return "Rock Toss";
				case 588:	return "Destruction Head";
				case 589:	return "Boulder Duty";
				case 590:	return "Mystical Fire";
				case 591:	return "Trick Room";
				case 592:	return "Venusaur Boss";
				case 593:	return "Tree Boss";
				case 594:	return "Sceptile Boss";
				case 595:	return "Torterra Boss";
				case 596:	return "Simisage Boss";
				case 597:	return "Serperior Boss";
				case 598:	return "Meganium Boss";
				case 599:	return "Oddish Boss";
				case 600:	return "Victreebel Boss";
				case 601:	return "Needle Arm";
				case 602:	return "Spiky Shield";
				case 603:	return "Mat Block";
				case 604:	return "Water Shuriken";
				case 605:	return "Parting Shot";
				case 606:	return "Snorlax Boss Scared Thoughts";
				case 607:	return "Lugia Boss Deadly Gust";
				case 608:	return "Misdreavus Boss Self Image";
				case 609:	return "Wobbuffet Boss Counter Spin";
				case 610:	return "Frenzy Plant";
				case 611:	return "Blast Burn";
				case 612:	return "Hydro Cannon";
				case 613:	return "Draco Meteor";
				case 614:	return "Giga Blast";
				case 615:	return "Sacred Fist";
				case 616:	return "Flock Flight";
				case 617:	return "Sludge Blast";
				case 618:	return "Sand Blast";
				case 619:	return "Rock Missiles";
				case 620:	return "Web Blast";
				case 621:	return "Image Blast";
				case 622:	return "Metal Blast";
				case 623:	return "Zap Blast";
				case 624:	return "Psychic Blast";
				case 625:	return "Ice Blast";
				case 626:	return "Shadow Blast";
				case 627:	return "Dark Blast";
				case 628:	return "Fairy Blast";
				case 629:	return "Flying Press";
				case 630:	return "Aeroblast";
				case 631:	return "Sacred Fire";
				case 632:	return "Thief";
				case 633:	return "Luster Purge";
				case 634:	return "Mist Ball";
				case 635:	return "Psycho Boost";
				case 636:	return "Crush Grip";
				case 637:	return "Assist";
				case 638:	return "Lunar Dance";
				case 639:	return "Total Moves";
			}
			return "Attack #" + num.toString();
		}
		
		public static const ITEMS_FUNC_NAME:String = "getItemName";
		public static const ITEMS_INDEX_START:int = 0;
		public static const ITEMS_INDEX_END:int = 79;
		public static function getItemName(num:int):String
		{
			switch(num)
			{
				case 0:		return "-";
				case 2:		return "Pokeball";
				case 3:		return "Potion";
				case 4:		return "Antidote";
				case 5:		return "Parlyz Heal";
				case 10:	return "Rare Candy";
				case 11:	return "Oran Berry";
				case 12:	return "Chilan Berry";
				case 13:	return "Everstone";
				case 14:	return "Neeverstone";
				case 15:	return "Gold Incense";
				case 16:	return "Dark Incense";
				case 17:	return "Friendship Doll";
				case 18:	return "Fire Stone";
				case 19:	return "Water Stone";
				case 20:	return "Thunder Stone";
				case 21:	return "Moon Stone";
				case 22:	return "Leaf Stone";
				case 23:	return "Dusk Stone";
				case 24:	return "Reaper Cloth";
				case 25:	return "Metal Coat";
				case 26:	return "Dawn Stone";
				case 27:	return "Sun Stone";
				case 28:	return "Awakening";
				case 29:	return "X Defend";
				case 30:	return "X Attack";
				case 31:	return "X Speed";
				case 32:	return "King Rock";
				case 33:	return "Super Potion";
				case 34:	return "Shiny Stone";
				case 35:	return "Silk Scarf";
				case 36:	return "Wide Lens";
				case 37:	return "Zoom Lens";
				case 38:	return "Smoke Ball";
				case 39:	return "Charcoal";
				case 40:	return "Miracle Seed";
				case 41:	return "Mystic Water";
				case 42:	return "Yellow Flute";
				case 43:	return "Metronome";
				case 44:	return "Revive";
				case 45:	return "Full Heal";
				case 46:	return "Burn Heal";
				case 47:	return "Ice Heal";
				case 48:	return "X Special Attack";
				case 49:	return "X Special Defense";
				case 50:	return "X Accuracy";
				case 51:	return "Guard Spec";
				case 52:	return "Dire Hit";
				case 53:	return "Manectite";
				case 54:	return "Wave Incense";
				case 55:	return "Sea Incense";
				case 56:	return "Lax Incense";
				case 57:	return "Full Incense";
				case 58:	return "Luck Incense";
				case 59:	return "Odd Incense";
				case 60:	return "Rock Incense";
				case 61:	return "Rose Incense";
				case 62:	return "Up Grade";
				case 63:	return "Dragon Scale";
				case 64:	return "Dubious Disc";
				case 65:	return "Electirizer";
				case 66:	return "Magmarizer";
				case 67:	return "Protector";
				case 68:	return "Oval Stone";
				case 69:	return "Razor Claw";
				case 70:	return "Razor Fang";
				case 71:	return "Aerodactylite";
				case 72:	return "Blastoisinite";
				case 73:	return "Ampharosite";
				case 74:	return "Venusaurite";
				case 75:	return "Blue Orb";
				case 76:	return "Red Orb";
				case 77:	return "Deep Sea Tooth";
				case 78:	return "Deep Sea Scale";
				case 79:	return "Pure Incense";
			}
			return "Item #" + num.toString() + " - INVALID";
		}
		
		public static function isItemLegal(num:int):Boolean
		{
			return getItemName(num).indexOf("INVALID") == -1;
		}
		
		public static const TYPE_FUNC_NAME:String = "getTypeName";
		public static const TYPE_INDEX_START:int = 1;
		public static const TYPE_INDEX_END:int = 17;
		public static function getTypeName(num:int):String
		{
			switch(num)
			{
				case 1:		return "Grass";
				case 2:		return "Poison";
				case 3:		return "Water";
				case 4:		return "Fire";
				case 5:		return "Normal";
				case 6:		return "Flying";
				case 7:		return "Bug";
				case 8:		return "Ghost";
				case 9:		return "Steel";
				case 10:	return "Rock";
				case 11:	return "Electric";
				case 12:	return "Ice";
				case 13:	return "Fight";
				case 14:	return "Ground";
				case 15:	return "Dragon";
				case 16:	return "Dark";
				case 17:	return "Physic";
			}
			return "Type #" + num.toString();
		}
		
		public static function canCapturePokemon(num:int, type:int = 0):Boolean
		{
			// Shiny
			if(type == 1)
			{
				switch(num)
				{
					case 10: return true;
					case 11: return true;
					case 12: return true;
					case 13: return true;
					case 14: return true;
					case 15: return true;
					case 16: return true;
					case 17: return true;
					case 18: return true;
					case 19: return true;
					case 20: return true;
					case 21: return true;
					case 22: return true;
					case 23: return true;
					case 24: return true;
					case 27: return true;
					case 28: return true;
					case 29: return true;
					case 30: return true;
					case 31: return true;
					case 32: return true;
					case 33: return true;
					case 34: return true;
					case 37: return true;
					case 38: return true;
					case 39: return true;
					case 40: return true;
					case 41: return true;
					case 42: return true;
					case 43: return true;
					case 44: return true;
					case 45: return true;
					case 46: return true;
					case 47: return true;
					case 48: return true;
					case 49: return true;
					case 52: return true;
					case 53: return true;
					case 54: return true;
					case 55: return true;
					case 56: return true;
					case 57: return true;
					case 58: return true;
					case 59: return true;
					case 60: return true;
					case 61: return true;
					case 62: return true;
					case 63: return true;
					case 64: return true;
					case 66: return true;
					case 67: return true;
					case 68: return true;
					case 69: return true;
					case 70: return true;
					case 71: return true;
					case 72: return true;
					case 73: return true;
					case 74: return true;
					case 75: return true;
					case 76: return true;
					case 79: return true;
					case 80: return true;
					case 81: return true;
					case 82: return true;
					case 83: return true;
					case 88: return true;
					case 89: return true;
					case 90: return true;
					case 91: return true;
					case 92: return true;
					case 93: return true;
					case 95: return true;
					case 96: return true;
					case 97: return true;
					case 98: return true;
					case 99: return true;
					case 102: return true;
					case 103: return true;
					case 108: return true;
					case 109: return true;
					case 110: return true;
					case 114: return true;
					case 118: return true;
					case 119: return true;
					case 120: return true;
					case 121: return true;
					case 123: return true;
					case 124: return true;
					case 127: return true;
					case 128: return true;
					case 129: return true;
					case 130: return true;
					case 131: return true;
					case 132: return true;
					case 147: return true;
					case 148: return true;
					case 149: return true;
					case 161: return true;
					case 162: return true;
					case 163: return true;
					case 164: return true;
					case 165: return true;
					case 166: return true;
					case 167: return true;
					case 168: return true;
					case 169: return true;
					case 170: return true;
					case 171: return true;
					case 172: return true;
					case 177: return true;
					case 178: return true;
					case 179: return true;
					case 180: return true;
					case 181: return true;
					case 183: return true;
					case 184: return true;
					case 186: return true;
					case 187: return true;
					case 188: return true;
					case 189: return true;
					case 190: return true;
					case 191: return true;
					case 192: return true;
					case 193: return true;
					case 194: return true;
					case 195: return true;
					case 198: return true;
					case 200: return true;
					case 201: return true;
					case 202: return true;
					case 203: return true;
					case 204: return true;
					case 205: return true;
					case 206: return true;
					case 207: return true;
					case 208: return true;
					case 209: return true;
					case 210: return true;
					case 211: return true;
					case 212: return true;
					case 213: return true;
					case 214: return true;
					case 215: return true;
					case 216: return true;
					case 217: return true;
					case 218: return true;
					case 219: return true;
					case 220: return true;
					case 221: return true;
					case 222: return true;
					case 223: return true;
					case 224: return true;
					case 225: return true;
					case 226: return true;
					case 227: return true;
					case 228: return true;
					case 229: return true;
					case 230: return true;
					case 231: return true;
					case 232: return true;
					case 233: return true;
					case 234: return true;
					case 235: return true;
					case 241: return true;
					case 243: return true;
					case 244: return true;
					case 245: return true;
					case 246: return true;
					case 247: return true;
					case 248: return true;
					case 252: return true;
					case 253: return true;
					case 254: return true;
					case 255: return true;
					case 256: return true;
					case 257: return true;
					case 258: return true;
					case 259: return true;
					case 260: return true;
					case 261: return true;
					case 262: return true;
					case 263: return true;
					case 264: return true;
					case 265: return true;
					case 266: return true;
					case 267: return true;
					case 268: return true;
					case 269: return true;
					case 270: return true;
					case 271: return true;
					case 272: return true;
					case 273: return true;
					case 274: return true;
					case 275: return true;
					case 276: return true;
					case 277: return true;
					case 278: return true;
					case 279: return true;
					case 280: return true;
					case 281: return true;
					case 282: return true;
					case 283: return true;
					case 284: return true;
					case 285: return true;
					case 286: return true;
					case 287: return true;
					case 288: return true;
					case 289: return true;
					case 290: return true;
					case 291: return true;
					case 292: return true;
					case 293: return true;
					case 294: return true;
					case 295: return true;
					case 296: return true;
					case 297: return true;
					case 298: return true;
					case 299: return true;
					case 300: return true;
					case 301: return true;
					case 302: return true;
					case 303: return true;
					case 304: return true;
					case 305: return true;
					case 306: return true;
					case 307: return true;
					case 308: return true;
					case 309: return true;
					case 310: return true;
					case 311: return true;
					case 312: return true;
					case 313: return true;
					case 314: return true;
					case 315: return true;
					case 316: return true;
					case 317: return true;
					case 318: return true;
					case 319: return true;
					case 320: return true;
					case 321: return true;
					case 322: return true;
					case 323: return true;
					case 324: return true;
					case 325: return true;
					case 326: return true;
					case 327: return true;
					case 328: return true;
					case 329: return true;
					case 330: return true;
					case 331: return true;
					case 332: return true;
					case 333: return true;
					case 334: return true;
					case 335: return true;
					case 336: return true;
					case 337: return true;
					case 338: return true;
					case 339: return true;
					case 340: return true;
					case 341: return true;
					case 342: return true;
					case 343: return true;
					case 344: return true;
					case 345: return true;
					case 346: return true;
					case 347: return true;
					case 348: return true;
					case 349: return true;
					case 350: return true;
					case 351: return true;
					case 352: return true;
					case 353: return true;
					case 354: return true;
					case 355: return true;
					case 356: return true;
					case 357: return true;
					case 358: return true;
					case 359: return true;
					case 360: return true;
					case 361: return true;
					case 362: return true;
					case 363: return true;
					case 364: return true;
					case 365: return true;
					case 366: return true;
					case 367: return true;
					case 368: return true;
					case 369: return true;
					case 370: return true;
					case 371: return true;
					case 372: return true;
					case 373: return true;
					case 374: return true;
					case 375: return true;
					case 376: return true;
					case 406: return true;
					case 407: return true;
					case 424: return true;
					case 427: return true;
					case 428: return true;
					case 429: return true;
					case 430: return true;
					case 433: return true;
					case 461: return true;
					case 462: return true;
					case 463: return true;
					case 464: return true;
					case 466: return true;
					case 467: return true;
					case 469: return true;
					case 472: return true;
					case 473: return true;
					case 474: return true;
					case 475: return true;
					case 476: return true;
					case 477: return true;
					case 478: return true;
				}
			}
			// Shadow
			else if(type == 2)
			{
				switch(num)
				{
					case 10: return true;
					case 11: return true;
					case 12: return true;
					case 13: return true;
					case 14: return true;
					case 15: return true;
					case 16: return true;
					case 17: return true;
					case 18: return true;
					case 19: return true;
					case 20: return true;
					case 21: return true;
					case 22: return true;
					case 23: return true;
					case 24: return true;
					case 27: return true;
					case 28: return true;
					case 29: return true;
					case 30: return true;
					case 31: return true;
					case 32: return true;
					case 33: return true;
					case 34: return true;
					case 37: return true;
					case 38: return true;
					case 39: return true;
					case 40: return true;
					case 41: return true;
					case 42: return true;
					case 43: return true;
					case 44: return true;
					case 45: return true;
					case 46: return true;
					case 47: return true;
					case 48: return true;
					case 49: return true;
					case 52: return true;
					case 53: return true;
					case 54: return true;
					case 55: return true;
					case 56: return true;
					case 57: return true;
					case 58: return true;
					case 59: return true;
					case 60: return true;
					case 61: return true;
					case 62: return true;
					case 63: return true;
					case 64: return true;
					case 66: return true;
					case 67: return true;
					case 68: return true;
					case 69: return true;
					case 70: return true;
					case 71: return true;
					case 72: return true;
					case 73: return true;
					case 74: return true;
					case 75: return true;
					case 76: return true;
					case 79: return true;
					case 80: return true;
					case 81: return true;
					case 82: return true;
					case 83: return true;
					case 88: return true;
					case 89: return true;
					case 90: return true;
					case 91: return true;
					case 92: return true;
					case 93: return true;
					case 95: return true;
					case 96: return true;
					case 97: return true;
					case 98: return true;
					case 99: return true;
					case 102: return true;
					case 103: return true;
					case 108: return true;
					case 109: return true;
					case 110: return true;
					case 114: return true;
					case 118: return true;
					case 119: return true;
					case 120: return true;
					case 121: return true;
					case 123: return true;
					case 124: return true;
					case 127: return true;
					case 128: return true;
					case 129: return true;
					case 130: return true;
					case 131: return true;
					case 132: return true;
					case 147: return true;
					case 148: return true;
					case 149: return true;
					case 161: return true;
					case 162: return true;
					case 163: return true;
					case 164: return true;
					case 165: return true;
					case 166: return true;
					case 167: return true;
					case 168: return true;
					case 169: return true;
					case 170: return true;
					case 171: return true;
					case 172: return true;
					case 177: return true;
					case 178: return true;
					case 179: return true;
					case 180: return true;
					case 181: return true;
					case 183: return true;
					case 184: return true;
					case 186: return true;
					case 187: return true;
					case 188: return true;
					case 189: return true;
					case 190: return true;
					case 191: return true;
					case 192: return true;
					case 193: return true;
					case 194: return true;
					case 195: return true;
					case 198: return true;
					case 200: return true;
					case 201: return true;
					case 202: return true;
					case 203: return true;
					case 204: return true;
					case 205: return true;
					case 206: return true;
					case 207: return true;
					case 208: return true;
					case 209: return true;
					case 210: return true;
					case 211: return true;
					case 212: return true;
					case 213: return true;
					case 214: return true;
					case 215: return true;
					case 216: return true;
					case 217: return true;
					case 218: return true;
					case 219: return true;
					case 220: return true;
					case 221: return true;
					case 222: return true;
					case 223: return true;
					case 224: return true;
					case 225: return true;
					case 226: return true;
					case 227: return true;
					case 228: return true;
					case 229: return true;
					case 230: return true;
					case 231: return true;
					case 232: return true;
					case 233: return true;
					case 234: return true;
					case 235: return true;
					case 241: return true;
					case 243: return true;
					case 244: return true;
					case 245: return true;
					case 246: return true;
					case 247: return true;
					case 248: return true;
					case 252: return true;
					case 253: return true;
					case 254: return true;
					case 255: return true;
					case 256: return true;
					case 257: return true;
					case 258: return true;
					case 259: return true;
					case 260: return true;
					case 261: return true;
					case 262: return true;
					case 263: return true;
					case 264: return true;
					case 265: return true;
					case 266: return true;
					case 267: return true;
					case 268: return true;
					case 269: return true;
					case 270: return true;
					case 271: return true;
					case 272: return true;
					case 273: return true;
					case 274: return true;
					case 275: return true;
					case 276: return true;
					case 277: return true;
					case 278: return true;
					case 279: return true;
					case 280: return true;
					case 281: return true;
					case 282: return true;
					case 283: return true;
					case 284: return true;
					case 285: return true;
					case 286: return true;
					case 287: return true;
					case 288: return true;
					case 289: return true;
					case 290: return true;
					case 291: return true;
					case 292: return true;
					case 293: return true;
					case 294: return true;
					case 295: return true;
					case 296: return true;
					case 297: return true;
					case 298: return true;
					case 299: return true;
					case 300: return true;
					case 301: return true;
					case 302: return true;
					case 303: return true;
					case 304: return true;
					case 305: return true;
					case 306: return true;
					case 307: return true;
					case 308: return true;
					case 309: return true;
					case 310: return true;
					case 311: return true;
					case 312: return true;
					case 313: return true;
					case 314: return true;
					case 315: return true;
					case 316: return true;
					case 317: return true;
					case 318: return true;
					case 319: return true;
					case 320: return true;
					case 321: return true;
					case 322: return true;
					case 323: return true;
					case 324: return true;
					case 325: return true;
					case 326: return true;
					case 327: return true;
					case 328: return true;
					case 329: return true;
					case 330: return true;
					case 331: return true;
					case 332: return true;
					case 333: return true;
					case 334: return true;
					case 335: return true;
					case 336: return true;
					case 337: return true;
					case 338: return true;
					case 339: return true;
					case 340: return true;
					case 341: return true;
					case 342: return true;
					case 343: return true;
					case 344: return true;
					case 345: return true;
					case 346: return true;
					case 347: return true;
					case 348: return true;
					case 349: return true;
					case 350: return true;
					case 351: return true;
					case 352: return true;
					case 353: return true;
					case 354: return true;
					case 355: return true;
					case 356: return true;
					case 357: return true;
					case 358: return true;
					case 359: return true;
					case 360: return true;
					case 361: return true;
					case 362: return true;
					case 363: return true;
					case 364: return true;
					case 365: return true;
					case 366: return true;
					case 367: return true;
					case 368: return true;
					case 369: return true;
					case 370: return true;
					case 371: return true;
					case 372: return true;
					case 373: return true;
					case 374: return true;
					case 375: return true;
					case 376: return true;
					case 406: return true;
					case 407: return true;
					case 424: return true;
					case 429: return true;
					case 430: return true;
					case 433: return true;
					case 461: return true;
					case 462: return true;
					case 463: return true;
					case 464: return true;
					case 466: return true;
					case 467: return true;
					case 469: return true;
					case 472: return true;
					case 473: return true;
					case 474: return true;
					case 475: return true;
					case 476: return true;
					case 477: return true;
					case 478: return true;
				}
			}
			// Normal
			else
			{
				switch(num)
				{
					case 10: return true;
					case 11: return true;
					case 12: return true;
					case 13: return true;
					case 14: return true;
					case 15: return true;
					case 16: return true;
					case 17: return true;
					case 18: return true;
					case 19: return true;
					case 20: return true;
					case 21: return true;
					case 22: return true;
					case 23: return true;
					case 24: return true;
					case 27: return true;
					case 28: return true;
					case 29: return true;
					case 30: return true;
					case 31: return true;
					case 32: return true;
					case 33: return true;
					case 34: return true;
					case 37: return true;
					case 38: return true;
					case 39: return true;
					case 40: return true;
					case 41: return true;
					case 42: return true;
					case 43: return true;
					case 44: return true;
					case 45: return true;
					case 46: return true;
					case 47: return true;
					case 48: return true;
					case 49: return true;
					case 52: return true;
					case 53: return true;
					case 54: return true;
					case 55: return true;
					case 56: return true;
					case 57: return true;
					case 58: return true;
					case 59: return true;
					case 60: return true;
					case 61: return true;
					case 62: return true;
					case 63: return true;
					case 64: return true;
					case 66: return true;
					case 67: return true;
					case 68: return true;
					case 69: return true;
					case 70: return true;
					case 71: return true;
					case 72: return true;
					case 73: return true;
					case 74: return true;
					case 75: return true;
					case 76: return true;
					case 79: return true;
					case 80: return true;
					case 81: return true;
					case 82: return true;
					case 83: return true;
					case 88: return true;
					case 89: return true;
					case 90: return true;
					case 91: return true;
					case 92: return true;
					case 93: return true;
					case 95: return true;
					case 96: return true;
					case 97: return true;
					case 98: return true;
					case 99: return true;
					case 102: return true;
					case 103: return true;
					case 108: return true;
					case 109: return true;
					case 110: return true;
					case 114: return true;
					case 118: return true;
					case 119: return true;
					case 120: return true;
					case 121: return true;
					case 123: return true;
					case 124: return true;
					case 127: return true;
					case 128: return true;
					case 129: return true;
					case 130: return true;
					case 131: return true;
					case 132: return true;
					case 147: return true;
					case 148: return true;
					case 149: return true;
					case 152: return true;
					case 153: return true;
					case 154: return true;
					case 155: return true;
					case 156: return true;
					case 157: return true;
					case 158: return true;
					case 159: return true;
					case 160: return true;
					case 161: return true;
					case 162: return true;
					case 163: return true;
					case 164: return true;
					case 165: return true;
					case 166: return true;
					case 167: return true;
					case 168: return true;
					case 169: return true;
					case 170: return true;
					case 171: return true;
					case 172: return true;
					case 175: return true;
					case 176: return true;
					case 177: return true;
					case 178: return true;
					case 179: return true;
					case 180: return true;
					case 181: return true;
					case 183: return true;
					case 184: return true;
					case 185: return true;
					case 186: return true;
					case 187: return true;
					case 188: return true;
					case 189: return true;
					case 190: return true;
					case 191: return true;
					case 192: return true;
					case 193: return true;
					case 194: return true;
					case 195: return true;
					case 198: return true;
					case 200: return true;
					case 201: return true;
					case 202: return true;
					case 203: return true;
					case 204: return true;
					case 205: return true;
					case 206: return true;
					case 207: return true;
					case 208: return true;
					case 209: return true;
					case 210: return true;
					case 211: return true;
					case 212: return true;
					case 213: return true;
					case 214: return true;
					case 215: return true;
					case 216: return true;
					case 217: return true;
					case 218: return true;
					case 219: return true;
					case 220: return true;
					case 221: return true;
					case 222: return true;
					case 223: return true;
					case 224: return true;
					case 225: return true;
					case 226: return true;
					case 227: return true;
					case 228: return true;
					case 229: return true;
					case 230: return true;
					case 231: return true;
					case 232: return true;
					case 233: return true;
					case 234: return true;
					case 235: return true;
					case 241: return true;
					case 243: return true;
					case 244: return true;
					case 245: return true;
					case 246: return true;
					case 247: return true;
					case 248: return true;
					case 252: return true;
					case 253: return true;
					case 254: return true;
					case 255: return true;
					case 256: return true;
					case 257: return true;
					case 258: return true;
					case 259: return true;
					case 260: return true;
					case 261: return true;
					case 262: return true;
					case 263: return true;
					case 264: return true;
					case 265: return true;
					case 266: return true;
					case 267: return true;
					case 268: return true;
					case 269: return true;
					case 270: return true;
					case 271: return true;
					case 272: return true;
					case 273: return true;
					case 274: return true;
					case 275: return true;
					case 276: return true;
					case 277: return true;
					case 278: return true;
					case 279: return true;
					case 280: return true;
					case 281: return true;
					case 282: return true;
					case 283: return true;
					case 284: return true;
					case 285: return true;
					case 286: return true;
					case 287: return true;
					case 288: return true;
					case 289: return true;
					case 290: return true;
					case 291: return true;
					case 292: return true;
					case 293: return true;
					case 294: return true;
					case 295: return true;
					case 296: return true;
					case 297: return true;
					case 298: return true;
					case 299: return true;
					case 300: return true;
					case 301: return true;
					case 302: return true;
					case 303: return true;
					case 304: return true;
					case 305: return true;
					case 306: return true;
					case 307: return true;
					case 308: return true;
					case 309: return true;
					case 310: return true;
					case 311: return true;
					case 312: return true;
					case 313: return true;
					case 314: return true;
					case 315: return true;
					case 316: return true;
					case 317: return true;
					case 318: return true;
					case 319: return true;
					case 320: return true;
					case 321: return true;
					case 322: return true;
					case 323: return true;
					case 324: return true;
					case 325: return true;
					case 326: return true;
					case 327: return true;
					case 328: return true;
					case 329: return true;
					case 330: return true;
					case 331: return true;
					case 332: return true;
					case 333: return true;
					case 334: return true;
					case 335: return true;
					case 336: return true;
					case 337: return true;
					case 338: return true;
					case 339: return true;
					case 340: return true;
					case 341: return true;
					case 342: return true;
					case 343: return true;
					case 344: return true;
					case 345: return true;
					case 346: return true;
					case 347: return true;
					case 348: return true;
					case 349: return true;
					case 350: return true;
					case 351: return true;
					case 352: return true;
					case 353: return true;
					case 354: return true;
					case 355: return true;
					case 356: return true;
					case 357: return true;
					case 358: return true;
					case 359: return true;
					case 360: return true;
					case 361: return true;
					case 362: return true;
					case 363: return true;
					case 364: return true;
					case 365: return true;
					case 366: return true;
					case 367: return true;
					case 368: return true;
					case 369: return true;
					case 370: return true;
					case 371: return true;
					case 372: return true;
					case 373: return true;
					case 374: return true;
					case 375: return true;
					case 376: return true;
					case 406: return true;
					case 407: return true;
					case 424: return true;
					case 429: return true;
					case 430: return true;
					case 433: return true;
					case 461: return true;
					case 462: return true;
					case 463: return true;
					case 464: return true;
					case 466: return true;
					case 467: return true;
					case 468: return true;
					case 469: return true;
					case 472: return true;
					case 473: return true;
					case 474: return true;
					case 475: return true;
					case 476: return true;
					case 477: return true;
					case 478: return true;
				}
			}
			return false;
		}
	}
}